version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/coding-challenge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mypassword123!
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"