# Stage 1: Build the application with maven
FROM maven:3.8.4-openjdk-17-slim as build
WORKDIR /app
COPY pom.xml ./

# download all required dependencies into one layer
RUN mvn -B dependency:go-offline

COPY src /app/src
RUN mvn -B package

# Stage 2: Run the application
FROM openjdk:17-jdk-slim
COPY --from=build /app/target/*.jar app.jar
EXPOSE 3000
ENTRYPOINT ["java","-jar","/app.jar"]